eventbrite/pysoa

- pysoa/client/client.py
- pysoa/client/router.py
- pysoa/server/schemas.py
- pysoa/server/server.py
- pysoa/server/settings.py
- pysoa/server/types.py
This provides a client_router object on both job requests and on action
request, and further moves everything that requires chaining from
control into context.
> Add context-chaining client router and move things into context

- pysoa/common/transport/asgi/core.py
Sentinel support has been improved. The transport will now refresh masters from Sentinel on a configurable cooldown, defaulting to 30 seconds. After each refresh, it recreates the channel layer if the masters have changed. It also takes into account the edge cases where Sentinel returns the wrong number of masters or returns masters out of order, both of which would break the channel layer's consistent hash sharding.
This code could be easily integrated into asgi-redis, but the ideal situation would be to patch redis-py to support the notion of "all masters" in its Sentinel class.
> Asgi transport overhaul

- pysoa/common/transport/__init__.py
- pysoa/common/transport/local.py
- pysoa/test/server.py
- pysoa/test/stub_service.py
This changes from a pair of classes that share deques to a single class that is both client and server transport, and so can store the information on itself in a threadsafe manner.
It _does_ use a slightly nasty trick to put itself as the server transport, but short of changing how settings work this is hard not to do.
> Rewrite local transport to be threadsafe and inlined more

- .gitignore
- pysoa/client/client.py
- pysoa/test/server.py
- tests/server_tests/test_actions.py
- Exclude PyCharm files using `.gitignore`.
- Fix a `pytest` warning when trying to collect a class that's not a test case.
- Add a `ServerTestCase#call_action` helper to make action calling easier within the scope of tests.
- Add `ServerTestCase` helpers `assertRunsWithErrorCodes`, `assertRunsWithOnlyErrorCodes`, `assertRunsWithFieldErrors`, and `assertRunsWithOnlyFieldErrors` to make asserting the presence of response errors much easier.
> Add helpers to ServerTestCase to make calling actions and asserting errors easier

- pysoa/client/client.py
- pysoa/client/settings.py
- pysoa/common/transport/asgi/settings.py
- pysoa/common/transport/local.py
- setup.py
Added back schema validation for ASGI transports, and added a new schema for local transports. 
Also added a new combined schema that works for any transport type and performs validation on ASGI or local transport settings, using a `Polymorph` field switched by the transport `'path'` value. This combined schema, called `PolymorphicClientSettings`, is the new default for the `Client` class. It still defaults to an ASGI transport when no path is provided.
> Client transport schema validation

- pysoa/client/client.py
- pysoa/client/expander.py
- tests/client_tests/test_expansions.py
- tests/client_tests/test_send_receive.py
This change does two things:
- Add the keyword argument `raise_action_errors` to `call_actions`, which defaults to `True`. If it is `True`, `call_actions` raises an exception when a response contains an action with errors, as before. If it is `False`, no exception will be raised.
- Add the option `raise_action_errors` to `ExpansionNode`, which defaults to `False`. It works the same way as the keyword argument, but at the level of expansions. This option is set in the `type_expansions` configuration, so that it can be configured on a field-by-field basis.
I've also added unit tests for all the new functionality.
> Improve error handling in `call_actions`

- pysoa/client/client.py
We expect switches set in the `Client.context` to be passed to all requests. Ensure that it is correctly merged with the switches passed in with the request arguments.
> Ensure that the Client passes switches from its context

- pysoa/common/transport/local.py
Restricting the `server_class` setting to a path was making it difficult to write unit tests using `ServerTestCase`, because we could not define a test server class inline and use it in the test case. This is a simple way to make it easier to write such tests without breaking existing uses of `LocalClientTransport`.
> LocalTransportSchema server class can be a path or a class object

- setup.py
Make version requirements use compatible versions rather than using `>=`.
> Use compatible versions in setup.py

- pysoa/common/transport/asgi/client.py
The use of `uuid1` here is not threadsafe, and can result in clients getting the wrong results back when multiple worker threads are spawned at once.
Thanks to @justecorruptio for pointing this out.
> Use uuid4 instead of uuid1 to calculate the client ID

- pysoa/common/settings.py
Support the `in` keyword for SOA settings so that you can easily check if a setting is present.
> Support `in` keyword for SOA settings

- pysoa/server/server.py
This will still cause the logger to include traceback information in log lines, while allowing different loggers to handle tracebacks their way.
The use case that prompted this was the `SentryHandler` from `raven`, which cannot correctly format exception information in Sentry requests without `exc_info`.
> Add exc_info option to logger.error statements

- docs/api.rst
- pysoa/client/client.py
- pysoa/common/metrics.py
- pysoa/common/schemas.py
- pysoa/common/settings.py
- pysoa/common/transport/asgi/client.py
- pysoa/common/transport/asgi/server.py
- pysoa/common/transport/base.py
- pysoa/common/transport/local.py
- pysoa/common/transport/redis_gateway/client.py
- pysoa/common/transport/redis_gateway/core.py
- pysoa/common/transport/redis_gateway/server.py
- pysoa/server/server.py
- pysoa/test/stub_service.py
- tests/common_tests/transport/redis_gateway/test_client.py
- tests/common_tests/transport/redis_gateway/test_server.py
- tests/common_tests/transport/test_asgi_transport.py
- Creates an interface for generic metrics recording
- Specifies a new configuration schema for setting up metrics that will be compatible with our current internal uses
- Integrates the recording of metrics into the server, client, and Redis transport. No effort is being expended on metricizing the ASGI transport, since it is being deprecated. No effort is being expended on metricizing the Local transport, as it has essentially no overhead compared to the client, which is metricized.
> Add support for recording metrics directly within SOA clients, servers, and transports

- pysoa/client/client.py
- pysoa/common/types.py
- pysoa/server/server.py
- tests/common_tests/test_test.py
This fixes issue #22. 
If the SOA client is on Python 2 while the server is on Python 3, or vice versa, they would not be able to communicate due to missing key errors, because the message keys on the Python 2 side would be serialized as non-unicode, while the keys on the Python 3 side would be expected to be unicode and would actually be bytes.
Here's the log output from the server running on Python 2 before the change:
```
2017-11-08 09:50:10,193    INFO: Job request: {'control': {u'continue_on_error': False}, 'context': {u'switches': [3], u'correlation_id': u'9895bc50c49e11e7bbad0242ac120029', u'caller': u'get_ip_location_from_request'}, 'actions': [{u'action': u'get_location_from_ip', u'body': {u'ip_address': u'172.18.0.1'}}]}
2017-11-08 09:50:10,195    INFO: Job response: {'errors': …
```
> Fix #22: Missing key issue when client and server on different Python versions

- docs/api.rst
- pysoa/client/client.py
- pysoa/common/transport/redis_gateway/core.py
Also adds some code that we will use for the transport cache, but it is not currently used until we get a baseline for metrics to which we can compare.
> Collect additional metrics to help identify client-creation bottlenecks

- pysoa/common/transport/redis_gateway/server.py
- setup.py
This was causing metrics to be recorded even if no requests were being sent in.
> Don't record receive timer in server if no message received

- docs/api.rst
- pysoa/client/client.py
- pysoa/common/transport/redis_gateway/backend/sentinel.py
- pysoa/common/transport/redis_gateway/core.py
- pysoa/common/transport/redis_gateway/settings.py
- pysoa/utils.py
- tests/common_tests/transport/redis_gateway/backend/test_sentinel.py
- tests/common_tests/transport/redis_gateway/test_core.py
- tests/test_utils.py
For other Redis-consuming projects, we have traditionally used the `sentinel_sharded_redis` library, which has a `sentinel_refresh_interval` setting. This setting controls how often `sentinel_sharded_redis` reaches out to Sentinel to get the latest information about Redis masters.
When consuming the `redis-py` library in this project, we applied the same pattern, adding a `sentinel_refresh_interval` setting to the transport and using that to control how often `redis-py`'s `sentinel.master_for(...)` is called. This is not the way `sentinel.master_for(...)` was designed to be used.
`sentinel.master_for(...)` creates a whole new `StrictRedis` client with a whole new connection pool every time it is called. We are wasting connections that remain open and unused until garbage collection runs, …
> Use master_for correctly to reduce number of Redis connections

- pysoa/client/client.py
- pysoa/test/stub_service.py
Everything else (settings, requests, responses, etc.) we enforce to be unicode. We don't enforce this for service names at the top level in the client, but we do at a lower level in the remote Redis transport. This results in hard-to-diagnose bugs that are often missed in testing (which uses a local transport).
> Ensure that service name passed to client is always unicode

- pysoa/client/client.py
- pysoa/common/transport/redis_gateway/core.py
We're currently serializing/deserializing the request/response in the client/server and then serializing/deserializing the entire message payload in the transport. There's no need to serialize in both places. This removes serialization from the client. The server will continue to support either, and then a future change will remove serialization from the server.
Our previous attempt to do this had to be rolled back because it was incompatible with the old ASGI transport. Now, nothing is using the old ASGI transport, so we can proceed with this.
> Attempt number two at removing duplicate serialization from the client

- pysoa/server/standalone.py
The double-import trap in the standalone helpers, meant to ensure that services' `standalone.py` files aren't called directly as runnable Python files, accidentally also trapped calls to the entrypoint executables. This fixes that.
> Ensure double-import trap doesn't catch entrypoint execution

- .gitignore
- pysoa/client/client.py
- tests/test/test_stub_service.py
This ensures we detect request/response mismatches when two clients
share the same underlying connection (otherwise you could have two
requests with value 0).
> Start request counter at a random value

- pysoa/common/transport/base.py
- pysoa/common/transport/redis_gateway/client.py
- tests/common_tests/transport/redis_gateway/test_client.py
- tests/common_tests/transport/redis_gateway/test_threading.py
When the transport cache is enabled, separate clients on separate threads with identical transport settings could get their responses mixed up, such that "client 2" could get responses meant for "client 1" and "client 1" responses meant for "client 2." So, that's bad. This commit fixes that and also adds a test to confirm the problem and a test to confirm the fix.
> Fix bug causing response mix-ups with transport cache

- pysoa/client/client.py
- tests/client_tests/test_expansions.py
- Refactor out expansion method in client
- renaming to differentiate expansion_config init v.s. expansion_query from request
- When make request, the `body` takes `[value]` instead of `value`, assuming we always call batch endpoints
- When expand, the initial `exp_service_requests` set to empty, because the upstream `service` has been called before this method.
> Refactor expansion

- pysoa/server/server.py
- pysoa/server/settings.py
For more verbose services, logging every request can get very expensive. However, request logging is on-or-off, which will hide the request log for requests that fail. This change permits separate logging levels for successful and failed requests.
> Add support for controlling request log logging level

- pysoa/server/__init__.py
- pysoa/server/action/base.py
- pysoa/server/action/introspection.py
- pysoa/server/action/status.py
- pysoa/server/server.py
- tests/server/action/test_introspection.py
- tests/server/action/test_status.py
This commit creates a new stock introspection action, which returns information about the service and its actions and their request and response schemas, and uses it by default if the server does not define an `introspect` action. As a related feature, it also ensures that every server responds to `status` if the server does not define a `status` action. Finally, it ensures the status action is adequately documented, so that it can be introspected well.
> Add support for server introspection

- tests/client/test_expansions.py
Renaming with well-known book-author to represent intuitive relations, instead of foo/bar/baz.
Also use different postfix to distinguish different roles of the names.
This makes future PRs easier to reason, e.g. https://github.com/eventbrite/pysoa/pull/64
> Renamings in test_expansion.py

- pysoa/server/settings.py
Using `fields.Any(fields.Boolean(), fields.UnicodeString())` for now so that this change is backwards-compatible. Whill change it to `fields.Boolean()` at a later date.
> Fix improper type for logging logger propagate setting

- pysoa/server/logging.py
- tests/server/test_logging.py
The logging context added in 157b6e8 works great for remote services. It even works for calling a local service from something other than another service. However, when a local or remote service calls a local service (such as when unit testing a service that calls another service and stubbing that other service), it results in an attribute error in the outer call. To properly support local services, which could be called more than one level deep, the logging context should be a stack, not an absolute value, to ensure that we properly step into and out of each context for logging purposes, so that logging calls include the correct details for our current position in the nested PySOA call stack.
> Ensure logging context works with local services by using a stack

- docs/api.rst
- pysoa/server/settings.py
When configuring Python logging with `dictConfig` (which the PySOA server does on startup), the `disable_existing_loggers` setting defaults to `True` for backwards compatibility with <2.6 versions of Python. This is true even in Python 3.6. The problem with this is that it is incompatible with code that instantiates a logger with `logging.getLogger` at the top of a module. When this code is first imported at startup, all loggers are initialized with a default config. When the new config is installed, all loggers not specifically mentioned in the new config are disabled (so they don't trickle to the root logger). This change sets `disable_existing_loggers` to `False` by default if not specified intentionally as `True`, which means that module-level `getLogger` calls triggered at import …
> Make disable_existing_loggers default to False to allow module-level getLogger

- pysoa/client/client.py
- pysoa/client/expander.py
- tests/client/test_expansions.py
Currently there are 5 issues with expansion, and this PR addresses the first 2.
Issues (current --- proposed fix)
1. source field is erased in response after expansion. --- source field should be kept untouched in response
2. expansion expect a singular endpoint, e.g. `get_xx_by_id`. --- expansion should expect a plural endpoint, e.g. `get_xxs_by_ids`, with additional layer of id-key.
3. expansion dispatch request one by one --- expansion should group requets by endpoint and do them in batch
4. expansion has no permission check --- TBD
5. expansion has no proper error handling or error code returned to the client --- TBD
The first 2 issue are easy to fix, as in thie PR
The third requires a overhaul, and will be in a separate PR
The 4th and 5th requires more discussion.
> Fix expansion response format

- pysoa/server/server.py
Previously, only job-level errors would cause the request logging to use the error log level. If action-level errors were encountered, the success log level would be used. This ensures the action-level errors also cause the error log level to be used for request logging.
> Ensure that action errors also trigger higher level logging

- pysoa/server/schemas.py
- tests/server/test_schemas.py
A job request without actions is not valid. It should trigger a validation error.
> Ensure actionless job request causes validation error

- pysoa/common/metrics.py
- setup.py
Currently, timer metrics default to millisecond resolution. With this change, timer metrics will now also support microsecond and nanosecond resolution.
> [MINOR] Add support for metric timer resolution

- pysoa/client/client.py
- pysoa/common/transport/redis_gateway/client.py
- pysoa/common/transport/redis_gateway/core.py
- pysoa/common/transport/redis_gateway/server.py
Due to the miniscule amount of time consumed by many operations in PySOA, millisecond resolution is not sufficient for metrics timers. This commit changes PySOA timers to microsecond resolution.
Note that this is a breaking change not for existing services/code, but for existing metrics graphs and reports. Previously, the value these graphs and reports displayed represented a number with milliseconds units. Now, they will be a number with microseconds units. As such, without the context of this change in mind, performance will appear to get worse by three orders of magnitude across the board on all existing graphs after a release deployment.
> [MAJOR] Switch to microsecond resolution for metrics timers

- pysoa/client/client.py
- tests/client/test_expansions.py
When doing expansion, a key exception should be silenced because it is a client error not a server error. Consequently return only the original skeleton_response.
> suppress expansion exception when request has invalid key

- pysoa/client/client.py
- pysoa/client/middleware.py
- pysoa/common/metrics.py
- pysoa/common/serializer/base.py
- pysoa/common/transport/base.py
- pysoa/common/transport/local.py
- pysoa/common/transport/redis_gateway/backend/base.py
- pysoa/common/transport/redis_gateway/client.py
- pysoa/common/transport/redis_gateway/core.py
- pysoa/server/action/base.py
- pysoa/server/action/status.py
- pysoa/server/autoreload.py
- pysoa/server/middleware.py
- pysoa/test/factories.py
- tests/client/test_send_receive.py
- tests/common/transport/redis_gateway/test_client.py
- tests/common/transport/redis_gateway/test_core.py
- tests/server/action/test_status.py
This adds support for setting a custom timeout when sending a request, so that users can shorten or lengthen the time the client will block waiting for a response. As part of this major refactor, we add proper `ABCMeta` to several class hierarchies.
> [MAJOR] Add support for setting a custom timeout when sending a request

- README.rst
- docs/api.rst
- docs/index.rst
- docs/testing.rst
- pysoa/client/client.py
- pysoa/server/action/status.py
- pysoa/test/stub_service.py
- setup.py
- tests/client/test_expansions.py
- tests/client/test_send_receive.py
- tests/server/action/test_status.py
- tests/test/test_stub_service.py
The PySOA communication protocol had innate support for parallel requests, but the client itself only supported serial requests. This large improvement commit does the following:
- Adds new methods to the client to support sending multiple requests to execute in parallel and then collect and return all responses blocking.
- Improves `stub_service` so that it works with these new methods.
- Writes extensive tests for parallel requests.
- Improves `BaseStatusAction` to do service client status checks in parallel.
- Improves the documentation to include information about parallel requests.
- Fixes some documentation that wasn't parsing properly in the GitHub viewer.
> [MAJOR] Support sending multiple requests to execute in parallel

- pysoa/test/stub_service.py
- tests/client/test_expansions.py
- tests/test/test_stub_service.py
The `stub_action` tool was wrapping `Client.call_actions` and `Client.call_jobs_parallel`, which resulted in expansions being completely ignored and not processed. This, itself, caused several problems, but it also meant that `Client.send_request` and `Client.get_all_responses` bypassed `stub_action` completely. This latest—and hopefully final—iteration of `stub_action` leaves `call_actions` and `call_jobs_parallel` alone and, instead, wraps `send_request` and `get_all_responses`. The result is that all routes to making a request pass through the stubbing code (when activated), and expansions are properly processed.
> [MINOR] Ensure stub_action supports expansions

- docs/api.rst
- pysoa/client/client.py
- pysoa/client/expander.py
- tests/client/test_expander.py
- tests/client/test_expansions.py
This change fixes the following several bugs in expansions:
- Expansions fail with `KeyError` if only some of the base objects contain the source field or action errors if the source field in one of the base objects is `None`.
- Expansions call expansion actions multiple times (once for every expansion object) instead of one time (with values from every expansion object). Fixing this required a major overhaul of the code that performs expansions.
- Expansions do not pass the correlation ID, context overrides, and control information from the parent request to the expansion requests, which can omit critical authentication information.
- Expansions do not properly process nested expansions unless the nested types and their routes have the same name, which can be extremely confusing. Fixing …
> [MAJOR] Fix several expansion bugs and refactor configuration

- pysoa/test/plan/grammar/__init__.py
The code was stripping to much indentation from auto-generated directive documentation, which was causing important contextual documentation to be lost. This uses a built-in method designed to remove leading and trailing blank lines and uniformly remove leading spaces from all remaining lines in Python docstrings so that contextual indentation is not lost.
> Improve auto-docs using built-in method designed for it

- pysoa/common/constants.py
- pysoa/server/action/base.py
- pysoa/server/errors.py
- pysoa/server/server.py
- setup.py
Conformity now supplies machine-readable error codes when validating schemas, so we should use those error codes instead of hard-coding `INVALID` as the error code.
> [MINOR]: Use error codes supplied by Conformity

- pysoa/test/compatibility.py
- pysoa/test/stub_service.py
- setup.py
- tests/client/test_expansions.py
- tests/client/test_send_receive.py
- tests/common/transport/redis_gateway/backend/test_sentinel.py
- tests/common/transport/redis_gateway/backend/test_standard.py
- tests/common/transport/redis_gateway/test_client.py
- tests/common/transport/redis_gateway/test_core.py
- tests/common/transport/redis_gateway/test_server.py
- tests/common/transport/redis_gateway/test_threading.py
- tests/server/test_autoreloader.py
- tests/server/test_logging.py
- tests/server/test_server/test_configuration.py
- tests/server/test_standalone.py
- tests/test/plan/test_plan_execution_errors.py
- tests/test/test_stub_service.py
We can conditionally import `unittest.mock` or `mock` for `stub_service` functionality, and for tests, instead of requiring the Mock backport library in Python 3.
> [MINOR] Don't require mock library for `stub_service`, tests in Python 3

- pysoa/common/constants.py
- pysoa/server/server.py
If a serialized response message is too large to send, resulting in a `MessageTooLarge` error, the error was trickling back all the way up to the server process loop, causing the server to shut down and the client to time out waiting for a response. This change ensures that, in such a case, an error response is sent to the client informing it that the response was too large to send, and then the server continues on with its business as usual instead of shutting down.
> [PATCH] Ensure an error response is sent if response too large

- pysoa/test/plugins/pytest.py
Test plans are supposed to be optional. But the failure to install tests plans makes the PyTest plugin fail to load. We can't make entry points (the plugin loading mechansim) optional, so we have to make the plugin do nothing if test plans aren't installed.
> [PATCH] Fix optionality of test plans

- pysoa/test/compatibility.py
If a project has Mock installed on Python 3, it probably means that project is using Mock. Their use of Mock combined with PySOA's test utils' use of `unittest.mock` can result in positional argument errors. PySOA must first make an effort to import Mock, and only use `unittest.mock` if Mock isn't installed.
> [PATCH] Import Mock if installed before unittest.mock

- pysoa/server/action/introspection.py
- pysoa/server/action/switched.py
- pysoa/server/internal/types.py
- pysoa/server/types.py
- tests/server/action/test_introspection.py
- tests/server/action/test_switched.py
Add a `SwitchedAction` class, which facilitates using different actions for a single given action name depending on which switch(es), if any, were sent with the request context.
> [MINOR] Add a SwitchedAction class to facilitate switch usage

- docs/api.rst
- docs/reference.rst
- pysoa/client/client.py
- pysoa/client/settings.py
- tests/client/test_send_receive.py
The transport cache (controlled by the `transport_cache_time_in_seconds` setting), was put in place before we got our Redis connection handling under control, when creating new transports took multiples of milliseconds. Now that we properly handle Redis connections with a thread-safe, global connection cache, creating new transports take nanoseconds, the same as retrieving transports from the cache. Additionaly, the cache is not thread-safe and introduces problems in multi-threaded environments.
As such, we are removing the transport cache from PySOA. This is a backwards-compatible change, because we are simply deprecating the `transport_cache_time_in_seconds` setting, and leaving it in place for some time. There will be a future, breaking change that removes this setting altogether. …
> [MINOR] Remove the transport cache as it is no longer needed

- docs/reference.rst
- docs/testing.rst
- docs/update_reference_docs.py
- pysoa/test/plan/grammar/__init__.py
- pysoa/test/plan/grammar/directives/__init__.py
- pysoa/test/plan/grammar/directives/api_capture.py
- pysoa/test/plan/grammar/directives/mock.py
- pysoa/test/plan/grammar/directives/stub_action.py
- tests/test/plan/mocking_and_stubbing/mocking_test.pysoa
- tests/test/plan/test_001_fixtures_work.py
- tests/test/plan/test_002_plugin_stats.py
- Add new directives to test plans to support using Mock for patching and expecting calls
- Fix a bug in documentation generation
- Update documentation with new directive documentation and fixed bug
> [MINOR] Add directives for using Mock from test plans

- .travis.yml
- pysoa/common/types.py
- pysoa/server/server.py
- tests/client/test_send_receive.py
We already have a request context, which includes things like the correlation ID, session ID, locale, authentication/authorization information, etc. We now have a need of a response context for the service to send job-level response information back to the client. (This change also removes support for Python 3.3, as the build tools we use no longer support it.)
This is a backwards-incompatible change. All service clients must be upgraded before service servers are upgraded. When a client deserializes a response, it sends the response dict to `JobResponse(**response_dict)`. This will error with an unexpected keyword argument `context` if the client hasn't been upgraded.
> [MAJOR] Add a response context dict to all responses

- docs/reference.rst
- docs/update_reference_docs.py
- pysoa/client/client.py
- pysoa/common/transport/redis_gateway/settings.py
- pysoa/server/server.py
- tests/client/test_send_receive.py
We've started using a send-and-forget concept, where we send a request but neither care about nor wait on a response. In these cases, the response the server sends needlessly sits in the Redis queue for 60 seconds until it expires. Using a `suppress_response` flag, you can now implement send-and-forget and instruct the server to not send a response, in order to conserve resources.
> [MINOR] Add option to suppress responses for send-and-forget

- pysoa/client/client.py
PySOA used to double-serialize. That was removed some time ago, but this remnant meta header was accidentally left behind. This removes it. Should be no side effects.
> [MINOR] Remove unused meta header for retired double-serialization

- docs/reference.rst
- docs/update_reference_docs.py
- pysoa/client/client.py
- pysoa/common/serializer/base.py
- pysoa/utils.py
- setup.py
- tests/client/test_send_receive.py
Now you can use `_future` versions of the `Client`'s `call_` methods to send requests and then perform other activities before obtaining the response using the returned future.
> [MAJOR] Add support for non-blocking client futures

- pysoa/server/server.py
- pysoa/server/standalone.py
If Django `settings.LOGGING` is present, Django will call `logging.config.dictConfig`. This can conflict with PySOA's call to `logging.config.dictConfig` with `settings.SOA_SERVER_SETTINGS['logging']`. This change ensures that the two logging configs are identical so that we'll have consistent behavior.
> [MINOR] Improve logging configuration to not conflict with Django

- pysoa/test/plugins/pytest/fixtures.py
This allows easier overriding of the service_client fixture in test modules
and plugins
> [PATCH] Extract server settings to a separate fixture

- docs/reference.rst
- docs/update_reference_docs.py
- pysoa/client/settings.py
- pysoa/common/schemas.py
- pysoa/common/settings.py
- pysoa/common/transport/local.py
- pysoa/common/transport/redis_gateway/client.py
- pysoa/common/transport/redis_gateway/server.py
- pysoa/server/server.py
- pysoa/server/settings.py
- pysoa/test/stub_service.py
- pysoa/utils.py
- tests/common/test_schemas.py
- tests/test/plan/test_002_plugin_stats.py
- tests/test/test_assertions.py
Before this change, if a consumer of PySOA (such as a service or another library) provides a new transport with a validated settings schema, the only way to use the transport and ensure the settings for it are validated is to also extend/override `PolymorphicServerSettings` and `PolymorphicClientSettings` and extend the `Client` to use the new transport settings class. This change makes the polymorphic client and server settings extensible by adding a `settings_schema` class attribute to a transport class.
> [MINOR] Make the polymorphic client and server settings extensible

- pysoa/common/settings.py
- pysoa/server/settings.py
The new setting `extra_fields_to_redact` was added in the wrong place. It should be in server settings, but it was added to common settings. The setting has no use to the client, so it should only be in server settings.
> [PATCH] Move extra_fields_to_redact from common to server settings

- tests/common/transport/redis_gateway/backend/test_sentinel.py
- tests/common/transport/redis_gateway/test_core.py
- tests/test/plan/grammar/test_tools.py
`assertEquals` has been deprecated [0] both in Python 2 and Python 3, in
favor of `assertEqual`.
[0] https://docs.python.org/3/library/unittest.html#deprecated-aliases
> [PATCH] Remove use of deprecated assertEquals

- pysoa/test/plan/grammar/directive.py
`setuptools` has deprecated the `EntryPoint.load` method in version
10.2 [0], and added a `resolve` method in version 11.3 [1], released in
January 2015.
[0] https://github.com/pypa/setuptools/blob/898c252e4c1d0521a106fb608993aef099dca16e/CHANGES.rst#102
[1] https://github.com/pypa/setuptools/commit/92a553d3adeb431cdf92b136ac9ccc3f2ef98bf1
> [PATCH] Remove use of deprecated EntryPoint.load

- pysoa/common/transport/redis_gateway/core.py
- pysoa/common/types.py
- pysoa/server/types.py
According to `attrs` changelog [0], the `convert` parameter is
deprecated since version 17.4.0. As `pysoa` can't use an older version
based on its requirements, the fix is just to change the argument on
existing calls.
[0] https://github.com/python-attrs/attrs/blob/c2bc83195727f7ba554913bde24ac61dfce33e9f/CHANGELOG.rst#deprecations-1
> [PATCH] Fix usage of deprecated attr.ib `convert` parameter

- pysoa/common/serializer/msgpack_serializer.py
- setup.py
- tests/common/transport/redis_gateway/backend/test_sentinel.py
- tests/common/transport/redis_gateway/backend/test_standard.py
Since `msgpack-python` version 0.5.2, the `encoding` parameter is deprecated. `raw=False` is the replacement for `encoding='utf-8'`. This commit makes that change and bumps the library to require at least 0.5.2.
Related warning message:
```
/usr/local/lib/python3.5/dist-packages/ebsoa/server/middleware/auth.py:137: PendingDeprecationWarning: encoding is deprecated, Use raw=False instead.
```
> [MINOR] Remove deprecated use of "encoding" argument in msgpack.unpackb

- pysoa/client/client.py
If a timeout is specified when calling the client functions to send a message, include that timeout in the control header so that services can be aware of that number if necessary / useful.
> [MINOR] If timeout specified, include it in the control header

- docs/testing.rst
- pysoa/test/stub_service.py
- tests/test/test_stub_service.py
This is currently possible only after the mock is returned by the context manager, which makes it impossible to define preconfigured stubs (specially when setting a callable that rely on variable data).
> [MINOR] Allow setting `side_effect` while defining the stub

- docs/reference.rst
- docs/update_reference_docs.py
- pysoa/common/logging.py
- pysoa/server/settings.py
- tests/common/test_logging.py
The Syslog logging handler built into Python has a crucial flaw: If the total, formatted log message exceeds the minimum interface MTU between the service and the Syslog server, that entire message is lost if sent over UDP (the default and best-performing option). It will either log the error or silently fail, but the message will be lost. Since PySOA logging includes request/response logging, which can be large, it means we can possibly lose a lot of logged information that we didn't expect to lose, without even know we lost it.
This commit provides an improvement on that built-in Syslog handler. At startup, it will attempt to determine the minimum MTU between the running process and the Syslog server, or make an educated guess if it can't (or set an upper boundary of 1MB over TCP and …
> [MINOR] A better Syslog logging handler

- pysoa/client/client.py
- pysoa/server/server.py
Server would shut down entirely if a request was received with non unicode keys in the context.  It appears to be a python issue when unpacking a dict with non-unicode keys into function arguments.
Not sure if something should be logged here.
The exception in this spot caused pysoa to choose to shutdown with:
2018-10-26 15:46:13,786   ERROR -- --: Unhandled server error; shutting down
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/pysoa/server/server.py", line 626, in run
self.handle_next_request()
File "/usr/local/lib/python3.5/dist-packages/pysoa/server/server.py", line 177, in handle_next_request
PySOALogContextFilter.set_logging_request_context(request_id=request_id, **job_request['context'])
TypeError: set_logging_request_context() keywords must be …
> [MINOR] Prevent server shutdown on request with non-unicode context keys

- pysoa/common/serializer/base.py
- pysoa/common/serializer/json_serializer.py
- pysoa/common/settings.py
- pysoa/common/transport/redis_gateway/core.py
- pysoa/common/transport/redis_gateway/settings.py
- tests/common/test_settings.py
- tests/common/transport/redis_gateway/test_core.py
This is the first step (commit) in a three-step (three-commit) breaking change to add support for switching the message serializer that the Redis transport uses based on a content-type header. There will be two more breaking commits in two future versions, in order to make migration possible.
Breaking changes in this commit/step:
- The Redis transport setting `serializer_config` has been renamed to `default_serializer_config` (it still defaults to the `MsgpackSerializer` like it did before, and it does not appear to be used anywhere at Eventbrite).
- The Redis transport "core" class attribute `serializer` has been renamed to `default_serializer` (it appeared to only be used in PySOA code).
Explanation of the steps:
- Step 1 (this commit): Rename the configuration setting, make the …
> [MAJOR] Add support for switching message serializer with content type header

- .travis.yml
- setup.py
This change supports, but does not require, newer versions of Attrs and PyTest and confirms proper operation with those. It also requires a newer patch version of Conformity and some other newer test-only dependencies. Finally, it removes the `sudo` requirement from the Python 3.7 Travis build.
> [PATCH] Support newer versions of several dependencies

- pysoa/server/server.py
We don't want to update the heartbeat file every request. We could tank the file system and kill performance. At most, it should be updated every 2.5 seconds.
> [PATCH] Throttle updates of the heartbeat file

- pysoa/test/compatibility.py
- tests/common/transport/redis_gateway/test_client.py
- tests/server/test_autoreloader.py
We were getting a ton of test warnings about deprecated `unittest.TestCase` methods. This commit allows us to use the new-to-Python-3.3 name in both Python 3 and Python 2.7.
> [PATCH] Update test compatibility tools to eliminate warnings

- tests/test/plan/test_001_fixtures_work.py
- tests/test/plan/test_002_plugin_stats.py
PyTest 4.2.0 started running `PluginTestingOrderOfOperationsTestCase` even though it contains no tests. This caused errors and also caused plugin statistics to fail. This should address that problem.
> [PATCH] Fix test failures introduced by PyTest 4.2.0

- pysoa/client/client.py
Use the same timeout specified in the client for the main call
to wait for expansions responses.
> [PATCH] Use client timeout for expansions receive responses

- setup.py
- tests/test/plan/first_fixtures/002_advanced_features.pysoa
- tests/test/plan/skipped_fixtures/global_skip.pysoa
- tests/test/plan/test_001_fixtures_work.py
- tests/test/plan/test_002_plugin_stats.py
PyTest 4.2.0 introduced a regression which broke the tests in our test plans, but wasn't a deal-breaker, so we simply adapted to the breakage. The regression was fixed in 4.2.1, but the fix introduced a new feature (not a bug) that `@unittest.skip`-skipped classes won't even be handled by our test plan code, so we can't measure them in the plugin-testing tests. This commit adapts to that change and removes the adaptation to the fixed regression. At also adds some new assertions and information to help ensure this is still working, even with the new changes.
> [PATCH] Fix tests broken by latest PyTest version

- .dockerignore
- .gitignore
- Dockerfile
- README.rst
- conftest.py
- docs/update_reference_docs.py
- pysoa/server/internal/event_loop.py
- pysoa/server/server.py
- pysoa/server/types.py
- tests/server/internal/test_event_loop.py
- tox.ini
The PySOA server currently creates an `asyncio` event loop (if `asyncio` is available) and makes it available to jobs/actions. However, this event loop is never started and will never run scheduled tasks and coroutines.
This change creates and runs an `asyncio` event loop in a separate thread. This allows users to run async coroutines/tasks in the background.
NOTE: all coroutines/callbacks scheduled against this event loop must use the `*_threadsafe` methods. See the documentation here: https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading
> [PATCH] Run the event loop in a separate thread.

- .dockerignore
- .travis.yml
- Dockerfile
- README.rst
- pysoa/common/transport/redis_gateway/core.py
- pysoa/server/action/status.py
- setup.cfg
- tests/common/test_logging.py
- tests/common/transport/redis_gateway/test_core.py
- tests/server/action/test_status.py
- tox.ini
- tox.sh
This is the second step (commit) in a three-step (three-commit) breaking change to add support for switching the message serializer that the Redis transport uses based on a content-type header. There will be one more breaking commit in a future version, in order to make migration possible.
Breaking changes in this commit/step:
- All request and response messages the Redis transport sends now contain a leading content-type header containing the MIME type used for selecting the proper deserializer on the receiving end. Before you upgrade to PySOA version 0.58.0 and get this change, you must first upgrade all clients and servers to at least 0.55.0 but still less than 0.58.0; otherwise, older clients or servers might not understand messages they receive from clients and servers running 0.58.0 …
> [MAJOR] Step 2 in the message serializer content type header

- pysoa/server/server.py
- tests/server/test_server/test_handle_next_request.py
Servers receiving job requests missing 'control' or 'context' keys
would produce exceptions instead of the expected job response with
error codes.  This change removes assumptions Server.handle_next_request
has about the validity of the job request message and allows usual
error response handling for such messages.
> [PATCH] Fix exceptions being thrown for missing job request keys

- pysoa/server/autoreload.py
- tests/server/test_autoreloader.py
- tox.ini
Added another Tox config to run tests with PyInotify installed. Added additional tests that run only when PyInotify is installed. New tests pass without any changes to code.
> [PATCH] Use Tox to add tests for PyInotify

- pysoa/server/internal/event_loop.py
- pysoa/server/server.py
This fixes #161:
- The server was creating an async event loop and then, on shutdown, instructing it to shut down and waiting for it to do so. However, the server was never starting the async event loop thread, so it waited forever for it to shut down and had to be forefully killed. This change fixes that by starting the event loop thread.
- The async event loop thread's `join` method was not calling `super().join()`. As a result, it was not joining properly. This changes fixes that to properly join on the super thread.
> [PATCH] #161: Fix server to start event loop thread, thread to join properly

- pysoa/server/server.py
A bug was introduced for servers without `asyncio` support, because the
`_async_event_loop_thread` attribute is not set in that scenario, but we
try to access it by using `self._async_event_loop_thread` afterwards.
This guarantees we always have that attribute during Server
initialization.
> [PATCH] Guarantee Server always has _async_event_loop_thread attribute

- docs/reference.rst
- pysoa/server/server.py
- pysoa/server/types.py
- setup.cfg
- setup.py
- tests/server/test_types.py
Add a helper method to `EnrichedActionRequest` to make it easy to call other local actions within the same service. Also, make `EnrichedActionRequest` subclassable by adding a `request_class` attribute to the `Server` class.
> [MINOR] Add helper for calling local actions within other actions

- docs/reference.rst
- pysoa/server/server.py
- pysoa/server/settings.py
- pysoa/server/standalone.py
When using heartbeat files together with `--fork`, you either got errors on shutdown because all processes used the same heartbeat file, or you used `{{pid}}` in the heartbeat file template to create unique heartbeat files, but the file names were non-deterministic and, thus, useless for health checks. This commit enhances forking to send a unique, deterministic forked process ID to each fork child, and a `{{fid}}` replacement in the heartbeat file template to support using that in the heartbeat file name, so that you can have unique heartbeat files per-process that are also useful for healthchecks.
> [MINOR] Add forked process ID for creating deterministic heartbeat files

- pysoa/test/stub_service.py
- tests/test/test_stub_service.py
PR #170 makes multiple uses of the same `stub_action()` instance to
have different return values on each call. This fixes it, so they have
return the same instead.
> [PATCH] Return same stub in multiple uses of the same stub_action instance

- pysoa/server/settings.py
This patch fixes a couple of typos in the `DeprecationWarning` given by `PolymorphicServerSettings`.
> [PATCH] Fix misleading DeprecationWarning

- pysoa/server/server.py
During `perform_pre_request_actions`, we should commit metrics, so that they are published then in case the request takes a long time to process.
> [PATCH] Commit metrics during perform_pre_request_actions

- .travis.yml
- conftest.py
- lint.sh
- pysoa/common/compatibility.py
- pysoa/common/logging.py
- pysoa/common/settings.py
- pysoa/server/coroutine.py
- pysoa/server/internal/event_loop.py
- pysoa/server/server.py
- pysoa/server/settings.py
- setup.cfg
- setup.py
- test.sh
- tests/unit/common/test_compatibility_async.py
- tests/unit/common/test_compatibility_threading.py
- tests/unit/server/internal/test_event_loop.py
- tox.ini
- Add a compatibility layer with a `ContextVar` wrapper that uses thread locals in Python 2.7, the `contextvars` backport in Python 3.5-3.6, and the standard `contextvars` in Python 3.7+.
- Add a new middleware layer for wrapping coroutines executed by the `AsyncEventLoopThread` (`request.run_coroutine`): `CoroutineMiddleware`.
- Remove all uses of thread locals and replace them with the `ContextVar` compatibility layer.
> [MINOR] Add robust support for safe asynchronous code

- pysoa/server/autoreload.py
- pysoa/server/server.py
- pysoa/server/standalone.py
- Add a `pre_fork` hook to the `Server` class to perform parent-process setup tasks right before spawning child sub-processes.
- Clean up `print` statements that printed out of order, replacing them with usages of `sys.stdout.write` and `sys.stdout.flush`.
> [MINOR] Add pre-fork hook method to Server class, clean up prints

- pysoa/common/serializer/msgpack_serializer.py
- setup.py
- tests/unit/common/test_serializers.py
`MsgpackSerializer` now supports both naive and UTC-aware `datetime.datetime` objects. Other time zones, however, are not supported. This is a breaking change, because sending a UTC-aware `datetime` from a client to a server on an older version will cause deserialization errors and you will get an error response. Be sure that all servers are running this version of PySOA before sending requests contaiting UTC-aware `datetime` objects.
> [MAJOR] Support UTC-aware datetime objects in MsgpackSerializer

- pysoa/__init__.py
- pysoa/server/server.py
- pysoa/typing_patches.py
- Fix the import errors in Python 3.5.2/3.6.1 due to missing stuff
- Fix Harakiri logging
> [PATCH] Fix import errors in Python 3.5.2/3.6.1 and fix Harakiri logging

- docs/reference.rst
- docs/update_reference_docs.py
- pysoa/client/expander.py
- pysoa/client/settings.py
- pysoa/common/settings.py
- pysoa/server/settings.py
- pysoa/test/stub_service.py
- setup.py
- tests/unit/common/test_settings.py
Use Conformity 1.26's new `Settings` and other features in order to remove a bunch of code from PySOA and deprecated PySOA's `Settings`.
> [MINOR] Use Conformity's Settings and deprecate PySOA's Settings

- pysoa/test/assertions.py
The test assertion helpers were not permissive about string types, so on Python 2 plain strings were iterated into a set of one-character error codes while unicode strings were (properly) turned into a single-element set of the error code. This fixes that regression.
> [PATCH] Be permissive about string types in assertions

- pysoa/common/metrics.py
- pysoa/server/internal/types.py
- pysoa/test/plan/__init__.py
- pysoa/test/plan/grammar/directives/expects_errors.py
- pysoa/test/stub_service.py
- setup.py
- tests/integration/test_send_receive.py
- tests/unit/test/test_stub_service.py
- tox.ini
Since we weren't transmitting `is_caller_error` between client and server unless the client reported that it was running version 0.70.0 or newer, certain tests that were passing before PySOA 0.70.0 was released started failing after it was released, because `is_caller_error` started getting transmitted in the correct situations. In a sense, this pass-before-fail-after behavior actually verified that our blacklisting of the attribute for older clients worked properly. This simple commit fixes those four breaking tests.
> [PATCH] Fix tests broken by releasing 0.70.0

- pysoa/client/client.py
- pysoa/client/middleware.py
- pysoa/server/middleware.py
- pysoa/server/server.py
- pysoa/server/types.py
- tests/integration/test_send_receive.py
- tests/unit/server/test_server/test_process_job.py
- [MINOR] Add a new server-side ``EnrichedJobRequest`` class to correspond to the server-side ``EnrichedActionRequest``.
- [MAJOR] Refactor the ``ServerMiddleware.job`` interface to accept the ``EnrichedJobRequest`` class instead of a dictionary.
- [MAJOR] Refactor the way middleware and middleware wrapper stacks are constructed to improve performance.
> [MAJOR] Implement #197: Refactor ServerMiddleware job with EnrichedJobRequest

- pysoa/test/plan/__init__.py
- pysoa/test/server.py
- pysoa/test/stub_service.py
- tests/unit/client/test_expander.py
- tests/unit/server/internal/test_event_loop.py
- tests/unit/server/test_server/test_configuration.py
- tests/unit/server/test_server/test_handle_next_request.py
- tests/unit/server/test_server/test_process_job.py
- tests/unit/test/test_server_test_cases.py
- Add the `assertLogs` method that is missing from `PyTestServerTestCase` and causing test failures in services.
- Fix the `assertCountEqual` implementation in `PyTestServerTestCase` to resolve some test failures in services (and deprecate it, because we have to rely on private CPython methods to use it).
- Rename some tests to use a standard naming scheme.
> [PATCH] Add missing assertLogs, fix assertCountEqual, rename some tests

- pysoa/test/plan/__init__.py
- pysoa/test/server.py
- pysoa/test/stub_service.py
Before we import from `typing_extensions`, we should always first try to import from `typing`.
> [PATCH] Try importing from typing before typing_extensions

- pysoa/server/server.py
- pysoa/test/server.py
- tests/functional/test_very_large_responses.py
- tox.ini
This should prevent the following error:
```
RuntimeError: Database access not allowed, use the "django_db" mark, or the "db" or "transactional_db" fixtures to enable it.
```
> [PATCH] Skip Django database connection cleanup in unit tests

- pysoa/test/stub_service.py
- tests/unit/test/test_stub_service.py
`stub_action` was not properly popping certain responses from the collection of outstanding responses when those responses were retrieved. As a result, if a `stub_action` call specified a `side_effect`, and one of those side effects was an exception, and other non-exception side effects followed the exception, the exception masked all future side effects. This is now fixed.
> [PATCH] Fix #239: stub_action side_effect now supports mix of types

- pysoa/common/serializer/json_serializer.py
- pysoa/common/serializer/msgpack_serializer.py
- setup.py
- `msgpack-python` is a deprecated PyPi dependency. The library has been renamed to `msgpack`, and changing this is the only way to get the latest bug fixes. There are no breaking changes between these libraries (same module name, just a different paackage name).
- The serializers were masking the underlying error type and message when errors were encountered. This fixes that.
> [PATCH] Improve error messages and use correct msgpack dependency

- Dockerfile
- pysoa/common/transport/redis_gateway/core.py
- tests/unit/common/transport/redis_gateway/test_core.py
We were stripping whitespace from serialized messages when extracting header information. When messages were chunked and the chunk boundary landed on a whitespace character, this caused the re-assembled message to fail to deserialize, as described in #240. This commit resolves this issue.
> [PATCH] Fix #240 - Do not strip whitespace from serialized messages

- .travis.yml
- functional.sh
- tox.ini
Attempt to make Travis builds faster by consolidating the two Python 3.7 stages, eliminating the Python 3.6 stage, making functional tests start first, and running Docker builds in Parallel.
> [PATCH] Try to make Travis builds faster

- pysoa/server/server.py
- pysoa/test/plan/grammar/tools.py
- tests/integration/test/plan/first_fixtures/003_globals.pysoa
- tests/unit/test/plan/grammar/test_tools.py
Fixes https://github.com/eventbrite/pysoa/issues/255
if [_global_directives are filled](https://github.com/eventbrite/pysoa/blob/236ac4147b9cd3ff96150e80bf2bcbcf0283c2b5/pysoa/test/plan/parser.py#L273) is used `get_all_paths` to recursively define where put each value detailed on the current test_case.
The iterable-like types are traveled for each item but for empty cases `{}` or `[]` this doesn't happen.
We'll check before doing the iteration block if are truth-ty values and if not return the current_path value.
> [PATCH] Fix handling of empty structures in `get_all_paths`

- pysoa/server/action/introspection.py
- pysoa/server/server.py
- pysoa/server/types.py
Currently, it is more difficult than it needs to be to add information to the `introspect` action responses. This change allows a service implementer to easily override the default introspection action.
> [MINOR] Allow Server subclasses to set a custom introspection action

- pysoa/server/server.py
- pysoa/test/stub_service.py
Register stub responses and requests in stub_action for use in prototype contract testing
> Capture stubs to autogenerate schemas for contract testing

- pysoa/test/plan/grammar/data_types.py
- tests/unit/test/plan/grammar/test_data_types.py
As part of feature parity with our deprecated library of test-plans, we need to support for date-times represented as strings for `expect any` grammar ([related code in Legacy SOA](https://github.com/eventbrite/soa/blob/7.34.4/service/test/test_plan/data_types.py#L75-L99)).
> [MINOR] Treat UTC datetime strings as datetimes in test plans

- pysoa/common/transport/base.py
- pysoa/common/transport/local.py
- pysoa/common/transport/redis_gateway/server.py
- pysoa/server/server.py
- tests/unit/common/transport/redis_gateway/test_server.py
- tests/unit/common/transport/redis_gateway/test_threading.py
- tests/unit/server/test_server/test_handle_next_request.py
This will allow the transport to know which forked process it is,
which is necessary if transport instances are sharing resources
like ports.
> [MINOR] Pass instance index into transport.

- docs/api.rst
- docs/protocol.rst
Document that ``chunking`` is not compatible with ``parallel`` call
variants.
> [PATCH] Document race condition on chunk + parallel actions

- Dockerfile
- setup.py
- tests/functional/docker/Dockerfile-mysql
- tests/functional/docker/docker-compose.yaml
Tests were not working anymore because they were using a deprecated Ubuntu version (16.04).
This PR updates the Dockerfile to use the newest available (22.04 was not an option because [it does not support Python 3.5 anymore](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa)).
I needed to make some adjustments to make everything work with the new Ubuntu version:
In the Dockerfile:
- `ENV DEBIAN_FRONTEND=noninteractive` to avoid showing [this prompt](https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai)
- `python3.6-distutils` and `python3.7-distutils` seems to not be core python packages anymore in new Ubuntu versions.
- Regular `get-pip.py` doesn't support Python 3.6 anymore, you need to fetch it separately
Some other …
> Use Ubuntu 20.04 in Dockerfile

- pysoa/common/serializer/msgpack_serializer.py
- tests/unit/common/test_serializers.py
This PR should fix [incident 617](https://eventbrite.slack.com/archives/C04FMN96BDY) that is being caused due to invalid utf-8 characters being returned from some service calls.
> [MINOR] EB-207224 -- fixed unicode serialization issue

- setup.py
Moving typing extensions to be a mypy only dependency.
> moved typing extensions into mypy requirement section
