eventbrite/pysoa

pysoa/client/client.py, pysoa/server/server.py
Serialization is already handled in the transport, and serializing in the client/server is redundant and unnecessary. The client side of the library will no longer serialize requests and will no longer deserialize responses. The server side of the library will detect whether it needs to deserialize requests / serialize responses based on meta information sent by the client. This way, we can upgrade all the servers first without breaking anything or changing any behavior, and then upgrade all the clients, at which point double-serialization will cease painlessly.
=> Phase out double-serialization in favor of transport-only serialization

docs/api.rst, pysoa/common/settings.py, pysoa/server/server.py, pysoa/server/settings.py, pysoa/test/factories.py, tests/common_tests/test_settings.py
- Remove duplicate serialization in the server now that all clients have stopped serializing requests
- Improve the server settings schema so that more thorough validation takes place
- Improve documentation around settings and configuration
=> Remove duplicate serialization in the server and improve schema and docs

docs/api.rst, pysoa/server/server.py, pysoa/server/standalone.py, setup.py
- Bump Attrs, Conformity, and PyTest
- Add standalone helper to eliminate lots of boilerplate code across services
- Fix a typo
=> Bump Attrs and Conformity and add standalone helpers

.travis.yml, pysoa/server/action/status.py, setup.cfg, setup.py, tests/server_tests/action/test_status.py
Also improves Travis build and Setup files to include proper information, release binary distribution wheels.
=> Improve status action to enable abbreviated responses when only the version is needed

.gitignore, tests/test/test_stub_service.py
Removing randint mock, which causes PR #50 to fail
=> Removing randint mock

pysoa/server/server.py
If Django support is enabled in a server, we need to reset the query log after each request and close broken database connections before and after each request and when the server is idle. This replicates Django request processing behavior. In his change, it is implemented in such a way that implementing services can extend this behavior if necessary.
=> Add support for clean-up operations before and after requests

pysoa/server/server.py
When unit tests are run, the Django test fixture transaction wrapping can break the PySOA server connection cleanup, manifesting as an strange atomic block error on the first database query within an action. This commit ensures we do not clean up connections if we're in the middle of a transaction, which solves that problem. It also ensures that connection cleanup failures caused by PyTest's `mark.django_db` test are ignored.
=> Fix unit test failures caused by Django connection cleanup

pysoa/server/server.py
If no `DATABASES` aliases are configured in the Django settings, attempting connection cleanup causes errors. So don't attempt said cleanup in this case.
=> [PATCH] If no databases are configured, do not attempt Django connection cleanup

pysoa/server/action/status.py, pysoa/test/stub_service.py, tests/server/action/test_status.py, tests/test/test_stub_service.py
This change adds the standard ability to include other services' `status` action response in the diagnostic information of the `status` action response of a service configured to call those other services. It also includes a small enhancement to `stub_action` necessary to fully test this change to the `BaseStatusAction`. Finally, it includes an enhancement to `BaseStatusAction` to pass the `request` object to `check_` methods.
=> Add stock ability to include other services' status in status

.travis.yml
Adding `pip` cache to Travis, as detailed in its docs [1], to speed up builds.
[1] https://docs.travis-ci.com/user/caching/#pip-cache
=> [PATCH] Add pip cache to Travis

pysoa/common/transport/redis_gateway/client.py
This adds a timeout metric counter whenever the client transport raises a MessageReceiveTimeout, to give us better insight into the frequency of such problems.
=> [PATCH] Add client receive timeout metric

docs/reference.rst, pysoa/server/server.py
This adds a static `Server` initializer method that can be used to patch settings and/or the server class or perform any other action that must take place before the `Server` class is instantiated.
=> [MINOR] Add static Server initializer to support settings and server patching

pysoa/server/server.py
Also streamline optional imports for better performance.
=> [MINOR] Fix database error sometimes encountered during idle cleanup

pysoa/common/logging.py, pysoa/common/settings.py, pysoa/server/server.py, setup.py
Added sensitive field to redact in logging: `invitation_token`
=> [PATCH] Allow extra keys to be censored via settings.

pysoa/common/logging.py
The Python logging system is not guaranteed to construct handlers a single time. It may re-construct them at random times. Calculating the minimum MTU is expensive, so we need to cache it to ensure we only do it once for a given address.
=> [PATCH] Add MTU cache to SyslogHandler to improve performance

docs/update_reference_docs.py, pysoa/test/plan/__init__.py, pysoa/test/plan/grammar/__init__.py, pysoa/test/plan/grammar/data_types.py, pysoa/test/plan/grammar/tools.py
Fix several new Flake8 issues that arose with the latest version of Flake8.
=> [PATCH] Fix new flake8 errors

pysoa/client/client.py, tests/client/test_send_receive.py
Keyword arguments `raise_job_errors` and `catch_transport_errors` worked only for `call_jobs_parallel[_future]` and not for `call_actions_parallel[_future]`. This commit makes them work for both circumstances.
=> [MINOR] Allow use of `raise_job_errors` and `catch_transport_errors`

pysoa/test/stub_service.py, tests/test/test_stub_service.py
Currently, using the same `stub_action()` instance more than once at the
same time, breaks how the `Client` works, because:
1. It generates infinite recursion when wrapping the `send_request` method.
2. It doesn't completely revert the stub, so the `Client` keeps stubbed.
These two scenarios are fixed by checking if the `stub_action` instance
is already enabled. If it is, the `__enter__` method becomes a no-op.
When it's not enabled, `__exit__` becomos a no-op`.
Added a unit test with the simplest scenario to reproduce the issue.
=> [PATCH] Allow multiple uses of the same stub_action instance

pysoa/server/server.py, pysoa/server/standalone.py, tests/unit/server/test_standalone.py
Most other server processes, such as uWSGI or Apache HTTPD, will respawn failed/crashed workers when running in forking mode (also called prefork). PySOA did not do that until now. This change effects the following:
- By default, when running in forking mode, PySOA will respawn crashed workers.
- If a worker crashes 3 times in 15 seconds or 8 times in 60 seconds, PySOA will give up and stop respawning that worker.
- The new `--no-respawn` argument can disable this behavior if necessary.
- If all workers crash too many times and PySOA runs out of workers, it exits (this is basically the existing behavior, except for the above-described respawning).
To be clear, this existing behavior is unchanged:
- If the parent PySOA process receives `SIGTERM` or `SIGINT`, it terminates all workers …
=> [MINOR] Respawn crashed workers when running in forking mode

pysoa/server/server.py
- `make_client` now copies the `context` argument and adds a `calling_service` value to it before creating the client
- Subclasses can now pass more data to the `extra_context` to be added to the `context`
- Subclasses can now pass keyword arguments to be passed to the `Client` constructor
=> [MINOR] Improve `Server.make_client`, including with adding `calling_service`

pysoa/server/server.py
Implement #219: Now that we're using PyMetrics, we can move some once-internal metrics logic into PySOA proper, which improves the accuracy of those metrics and decreases the surface area of our internal code.
=> [MINOR] Add gauges to track running and busy PySOA workers

.travis.yml, Dockerfile, setup.cfg, tox.ini
=> [PATCH] Add support for Python 3.8

pysoa/common/logging.py, pysoa/common/transport/base.py, pysoa/server/autoreload.py, pysoa/test/plugins/pytest/plans.py, pysoa/typing_patches.py, setup.py, tests/integration/test_expansions.py, tests/integration/test_send_receive.py, tests/unit/server/action/test_base.py, tests/unit/server/action/test_switched.py, tests/unit/server/internal/test_event_loop.py, tests/unit/test/plan/grammar/test_tools.py, tests/unit/test/plan/test_plan_execution_errors.py, tests/unit/test/test_stub_service.py
This commit only fixes typing issues. It does not contain any behavioral or functional changes.
=> [PATCH] Fix new typing issues in MyPy 0.740

pysoa/test/plugins/pytest/plans.py
Officially, PySOA supports only PyTest 4.2+, but internally we need to account for the potential that ``PytestCollectionWarning`` might be missing in some projects.
=> [PATCH] Account for potential missing PytestCollectionWarning

pysoa/test/plugins/pytest/fixtures.py
Similar to 037cb2f2f5c717b67264c396654966002ef17c8d, we also need to skip Django database connection cleanup when the local client is created as a PyTest fixture. Note that this may look like a breaking change, but it is not. These fixtures do not get called directly; rather, PyTest calls them and automatically adjusts parameters as necessary, so this is a safe change.
=> [PATCH] Skip Django database connection cleanup in PyTest fixtures

pysoa/client/client.py, tests/integration/test_expansions.py
- Prevent infinite expansion recursion by preventing values that have already been expanded from being expanded again.
- Ensure top-level expansions are applied to all levels of objects.
=> [PATCH] Fix two bugs regarding client expansions

.codeclimate.yml
https://docs.google.com/document/d/1mdv9UKJp6-Ty1WQAoLjzsnZqoOxzCk42X1tdgifbExA/edit
=> [MINOR] Set up the CodeClimate configuration file

.travis.yml, Dockerfile, pysoa/common/logging.py, setup.cfg, setup.py, tests/functional/services/user/user_service/migrations/001_initial.py, tests/functional/services/user/user_service/server.py, tests/functional/test_yyy_forking_and_reloading.py, tests/integration/test/plan/test_001_fixtures_work.py, tests/integration/test/plan/test_002_plugin_stats.py, tests/unit/common/test_logging.py, tests/unit/server/test_standalone.py, tox.ini
Fixed the following commands:
- tox -e py38-mypy
- tox -e py37-mypy
- tox -e py35-pyinotify
- tox -e py27-attrs18
Fixed unit and functional tests
Removed:
- Travis testing for Python 3.8
- Dockerfile testing for python2.7 and 3.5
=> [MINOR] Fix pysoa build

.travis.yml, setup.py, tox.ini
Make PySOA compatible with newer versions of attrs
=> Make PySOA compatible with newer versions of attrs
